version: "3.7"

services:
  nginx:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3333:80"
    volumes:
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/mediafiles

volumes:
  static_volume:
  media_volume:
