version: "3.7"

services:
  nginx:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 80
    volumes:
      - /home/radif/www/etc:/etc
      - /home/radif/www/var:/var

volumes:
  /home/radif/www/etc:
  /home/radif/www/var:
