version: "3.7"

services:
  nginx:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /home/radif/www:/var/www