version: "3.7"

services:
  nginx:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - www-html:/var/www/html
      
volumes:
  www-html:
    