version: "3.7"

services:
  nginx:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 80
    volumes:
      - /etc/letsencrypt/live:/etc/letsencrypt/live
      - /home/radif/www:/home/radif/www
      - nginx:/etc/nginx

volumes:
    nginx:
    