version: "3.7"

services:
  nginx:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - www-html:/var/www/html
      - /home/radif/www/etc/letsencrypt:/etc/letsencrypt
      - /home/radif/www/etc/nginx:/etc/nginx

volumes:
  www-html:
